#ifndef ARM_TRIM_INPUT_CONFIG_H
#define ARM_TRIM_INPUT_CONFIG_H

#ifndef ARM_TRIM_INPUT_LEASE_MS
#define ARM_TRIM_INPUT_LEASE_MS 500U
#endif
#ifndef ARM_TRIM_PROFILE_MOVE_MS
#define ARM_TRIM_PROFILE_MOVE_MS 2000U
#endif
#ifndef ARM_TRIM_PROFILE_GUARD_MS
#define ARM_TRIM_PROFILE_GUARD_MS 300U
#endif
#ifndef ARM_TRIM_GRIP_MOVE_MS
#define ARM_TRIM_GRIP_MOVE_MS 1500U
#endif
#ifndef ARM_TRIM_GRIP_GUARD_MS
#define ARM_TRIM_GRIP_GUARD_MS 300U
#endif

#endif
