#ifndef LASER_CONFIG_H
#define LASER_CONFIG_H

#include "main.h"

#define LASER_TRIGGER_GPIO_PORT GPIOC
#define LASER_TRIGGER_GPIO_PIN GPIO_PIN_3
#define LASER_TRIGGER_GPIO_CLK_ENABLE() __HAL_RCC_GPIOC_CLK_ENABLE()
#define LASER_HOLD_MS 2000U


#endif
